#!/bin/sh

python utils/scripts/createdb.py
python manage.py syncdb --noinput
python utils/scripts/mkadmin.py
mkdir -p /home/dotcloud/data/media /home/dotcloud/volatile/static
python manage.py collectstatic --noinput
